-- =============================================================================
-- Migration 028: the caveat rule, stated at the table — thought_work_claims.
--                last_error on a succeeded row, and release_thought's p_error
--                (SMD-1052)
-- =============================================================================
--
-- WHY
--   015 gave `thought_work_claims.last_error` one meaning: on a failed row, why
--   it failed. SMD-1021 (FORK.md change 34) gave it a second: on a SUCCEEDED
--   row, when set, it is a CAVEAT — the write stands, and this is what the
--   worker could not do. The first caveat written is the head window: a long
--   thought the provider REFUSED to embed whole (a 413, or a 400 naming the
--   length) has its head window's vector stored, as a capture would have stored
--   it, and its claim is succeeded because that vector is the provider's final
--   answer — with the refusal written on the row. The second is the operator's
--   (SMD-1067): `--accept-failed` marks a row the provider refuses permanently
--   succeeded with `kept the vector it had; accepted by the operator: <the
--   failure>`. `db/reembed.ts` applies the rule through ONE predicate
--   (`withCaveat()`: status = 'succeeded' AND last_error IS NOT NULL) for the
--   count, the list and `--retry-fallbacks`, and states it in its header;
--   `db/README.md` states it too.
--
--   The schema said nothing. 015's COMMENTs cover `work_type`, `worker_id` and
--   `attempt_count`, not `last_error`; `release_thought`'s says only "Mark one
--   claim succeeded or failed" and nothing about `p_error`, which it stores
--   whatever the status. So a reader of the table — psql's `\d+`, a future
--   consumer of the claim table — had no way to learn that a note on a
--   succeeded row IS the caveat, and that `--retry-fallbacks` will return every
--   such row to the pool. `db/extract-entities.ts`, the sibling over the same
--   table, releases success with NULL and so does not collide; a consumer that
--   put any other note there would be swept in silently.
--
--   015 is applied and cannot be edited (migrate.ts hashes the file). The
--   ticket hoped to ride a migration that touched this area anyway (SMD-1042's
--   backfill, 023, or a later redefinition); 023 landed without it and no
--   redefinition of release_thought is on the roadmap, so the two comments
--   travel alone. A docs-only migration is heavy for two statements, but the
--   alternative is the rule staying where a reader of the schema cannot see it.
--
-- WHAT
--   * COMMENT ON COLUMN thought_work_claims.last_error — both meanings, by
--     status, and the consequence under a reembed: key: every succeeded row
--     with a non-NULL last_error is read as a caveat — by reembed.ts (status,
--     the end-of-run counts, the retry-fallbacks flag) and by preflight's
--     re-embed pass check, each scoped to reembed keys. A consumer under its
--     own work_type key (extract-entities.ts) is never swept; the rule states
--     what the column MEANS everywhere and what is READ under those keys.
--   * COMMENT ON FUNCTION release_thought — re-issued with 015's sentence kept
--     and one added: p_error is stored whatever p_status is, and what it means
--     on success.
--
-- WHAT A SUCCESSOR REDEFINITION MUST CARRY
--   CREATE OR REPLACE FUNCTION keeps a function's comment; a re-issued COMMENT
--   ON FUNCTION replaces it. Any migration that redefines release_thought and
--   re-issues 015's one-sentence comment would silently drop the p_error
--   sentence. Keep it — db/test-schema.ts [27] asserts the live text of both
--   comments, so the drop fails the suite whichever migration causes it.
--
--   The flags are named without their leading dashes ("the retry-fallbacks
--   flag", not "--retry-fallbacks"): test [10] strips `--` to end of line
--   before scanning the migrations for Supabase-specific text, and its header
--   holds that no migration puts that sequence inside a string literal.
--
-- SAFETY
--   COMMENT ON is idempotent (it replaces the description). No DDL on data,
--   no function body changes, no ACL change, no placeholder. The column and
--   the signature exist since 015; nothing here is conditional on width.
--   test-upgrade.ts's shape comparison (columns and function signatures) is
--   unaffected.
-- =============================================================================

COMMENT ON COLUMN thought_work_claims.last_error IS
  'Two meanings, by status. On a failed row: why it failed (the worker''s last error, or claim_thoughts'' reason when the lease expired for the last allowed time). On a succeeded row, when set: a CAVEAT — the write stands, and this is what the worker could not do (a long thought stored with its head window''s vector because the provider refused the whole content; a failure the operator accepted with reembed.ts''s accept-failed flag, whose text begins with the prefix config.mjs spells as ACCEPTED_CAVEAT_PREFIX). NULL on a succeeded row is a clean success. Under a reembed: work_type key every reader of the pass — reembed.ts''s status output, its end-of-run counts and its retry-fallbacks flag, and preflight''s re-embed pass check — treats a succeeded row with a non-NULL last_error as a caveat, and the retry-fallbacks flag returns it to the pool; so a pass under such a key must not store any other note here on success. Rule: SMD-1021; stated here: SMD-1052.';

COMMENT ON FUNCTION release_thought(uuid, text, text, text, text) IS
  'Mark one claim succeeded or failed. Only the holder of a still-claimed row may; returns false otherwise (expired and re-leased, deleted, or never held). p_error is stored in last_error whatever p_status is: on failed, why it failed; on succeeded, when given, a caveat — the write stands, and this is what the worker could not do (see the column''s comment; under a reembed: key the retry-fallbacks flag returns every such row to the pool). Pass NULL for a clean success.';
