-- ============================================================================
-- Thought work claims — a blackboard for parallel workers
-- ============================================================================
--
-- A claim table plus RPCs that let many independent workers process the same
-- pool of thoughts in parallel without two of them grabbing the same thought.
-- Useful for any community batch pipeline: consolidation workers, enrichment,
-- embedding backfills, scoring passes, wiki synthesis — anything that fans a
-- queue of thoughts out across multiple processes.
--
-- How a claim stays exclusive (the race guard):
--   The table's PRIMARY KEY is (thought_id, work_type). claim_thoughts() inserts
--   candidate rows with INSERT ... ON CONFLICT (thought_id, work_type) DO NOTHING
--   and returns only the rows it actually inserted. The unique index is the
--   arbiter: when two workers submit the same id at the same time, PostgreSQL
--   lets exactly one INSERT win the row and the other conflicts out silently.
--   The loser simply gets that id absent from its result set. No row is ever
--   handed to two workers, with no advisory locks or SELECT ... FOR UPDATE
--   needed — the constraint does the mutual exclusion atomically.
--
-- TTL + stale-claim reaping:
--   Each claim carries ttl_expires_at. If a worker crashes (SIGKILL, lost
--   network, OOM) it never releases its claims, which would otherwise strand
--   those thoughts forever. claim_thoughts() reaps inline on every call: before
--   inserting, it DELETEs claims for this work_type whose status is 'claimed'
--   and whose ttl_expires_at is in the past, freeing the (thought_id, work_type)
--   slot for a fresh claim. Pick a TTL comfortably longer than one unit of work.
--
-- ID contract: public.thoughts.id is UUID in the canonical Open Brain setup, so
-- thought_id is UUID REFERENCES public.thoughts(id). worker_id is free-form text.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT EXISTS, and
-- CREATE OR REPLACE FUNCTION. Additive only — it never alters or drops a column
-- on public.thoughts. Every DELETE in this file is qualified with a WHERE
-- clause. Safe to re-run.
--
-- This fork (SMD-1250): migration 015 is this blackboard on a brain built by
-- db/migrate.ts — the same idea, a different table (an enqueued pool with a
-- 'pending' status, a lease that is NULL when not held, attempts counted from
-- zero) and a different claim_thoughts (the pool is the enqueued rows, not an
-- id list the caller hands in), with release_thought and
-- release_claims_for_worker under the same names AND signatures. Upstream's
-- statements, which followed this header, would therefore have replaced two
-- of 015's function bodies with no error, added a claim_thoughts overload
-- beside 015's, and rewritten 015's table and column comments; every one of
-- them targets 015's table, so all are removed and this file is a stub.
-- db/README.md documents the fork's functions and the three workers that use
-- them. scripts/check-fork-consistency.mjs check 7 fails the build if the
-- functions return.
-- ============================================================================

-- (upstream's table, indexes, policies, grants, comments and three RPCs
--  stood here; see the note above.)
