#!/usr/bin/env bun
/**
 * test-replay.ts — the CI replay gate (SMD-1295). Offline: real PostgreSQL 17 in
 * WASM (PGlite) with pgvector, no service container, no model, no key, under a
 * minute. It replays a committed, content-free fixture through the SHIPPED
 * retrieval and fails when recall@5 drops past the fixture's floor — so a
 * retrieval change that reorders the candidate scan is caught by the searches
 * people actually ran, not only by the one corpus the baseline saturates.
 *
 * The fixture (evals/fixtures/replay-fixture.json, regenerated by
 * evals/build-replay-fixture.ts) is seeded synthetic vectors — ids and numbers,
 * no text — which is what a real brain reduced to id+embedding looks like to the
 * vector arm this gate exercises. It is generated, not exported: the gate needs
 * VECTORS, and export-queries.ts emits query text + ids for eval-replay (which
 * runs against a live corpus's own vectors). A real deployment that wanted the
 * gate over its own corpus would redact its thoughts to id+embedding; here it is
 * synthetic so the repo can gate itself with no brain and no model.
 *
 * The floor has teeth, and this proves it: after asserting the shipped ranking
 * clears the floor, it replays RANDOM query vectors and asserts recall collapses
 * below it. A regression that scrambled the ranking would score like the random
 * arm and fail — the deliberate-regression check the ticket's Verify asks for,
 * self-contained rather than a git-revert.
 *
 *   bun db/test-replay.ts
 */

import { PGlite } from "@electric-sql/pglite";
import { vector } from "@electric-sql/pglite/vector";
import { pg_trgm } from "@electric-sql/pglite/contrib/pg_trgm";
import { readdirSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { migrationValues, substituteMigration, DEFAULT_TRGM_INDEX } from "./config.mjs";
import { createAssert, seededRandom } from "./test-support.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const { assert, report } = createAssert();

type Fixture = {
  dim: number;
  recallFloor: number;
  thoughts: { id: string; embedding: number[] }[];
  queries: { embedding: number[]; relevant: string[] }[];
};
const fixture: Fixture = JSON.parse(readFileSync(join(HERE, "..", "evals", "fixtures", "replay-fixture.json"), "utf8"));
const { dim, recallFloor, thoughts, queries } = fixture;

// Schema at the fixture's width (not the shipped default), so the committed
// vectors bind. Everything else is the real migration set.
const db = new PGlite({ extensions: { vector, pg_trgm } });
const MIGRATIONS = join(HERE, "migrations");
const files = readdirSync(MIGRATIONS).filter((f) => f.endsWith(".sql")).sort();
for (const f of files) {
  await db.exec(substituteMigration(readFileSync(join(MIGRATIONS, f), "utf8"),
    migrationValues({ dim, model: "replay-fixture", trgm: DEFAULT_TRGM_INDEX, backfillLimit: null })));
}

const vec = (v: number[]) => `[${v.join(",")}]`;
for (const t of thoughts) {
  await db.query(`INSERT INTO thoughts (id, content, embedding) VALUES ($1, $2, $3::vector)`,
    [t.id, `replay-thought ${t.id}`, vec(t.embedding)]);
}

const K = 10;
async function rankedIds(embedding: number[]): Promise<string[]> {
  const rows = (await db.query<{ id: string }>(
    `SELECT id FROM match_thoughts($1::vector, -1.0, ${K}, '{}'::jsonb)`, [vec(embedding)])).rows;
  return rows.map((r) => r.id);
}

function recall5(ranked: string[], relevant: string[]): number {
  const top5 = new Set(ranked.slice(0, 5));
  return relevant.filter((id) => top5.has(id)).length / relevant.length;
}

console.log(`[1] Replay the committed fixture: ${thoughts.length} thoughts, ${queries.length} queries, dim ${dim}, floor ${recallFloor}`);
let shippedSum = 0;
for (const q of queries) shippedSum += recall5(await rankedIds(q.embedding), q.relevant);
const shippedMean = shippedSum / queries.length;
// The floor is the contract. A perfect mean at HEAD is expected for this fixture
// but is NOT asserted: a legitimate retrieval change that nudges one gold from
// rank 1 to rank 3 still clears the floor and must stay green — only a drop past
// the floor fails. The mean is reported so a slide toward it is visible.
assert(shippedMean >= recallFloor, `shipped retrieval clears the recall@5 floor (${shippedMean.toFixed(3)} >= ${recallFloor})`);
console.log(`    mean recall@5 = ${shippedMean.toFixed(3)} (floor ${recallFloor}); at HEAD every gold is rank 1`);

console.log("\n[2] The floor has teeth: random query vectors collapse below it");
const { unitVector } = seededRandom(97531);
let randomSum = 0;
for (const q of queries) randomSum += recall5(await rankedIds(unitVector(dim)), q.relevant);
const randomMean = randomSum / queries.length;
assert(randomMean < recallFloor, `an unrelated ranking fails the floor (${randomMean.toFixed(3)} < ${recallFloor}) — a scrambling regression would score like this`);

await db.close();
report();
