-- Edge Function Cost Optimization migrations
-- Created: 2026-04-17
--
-- This fork (SMD-1250): upstream's file defined two functions here, both of
-- which a brain built by db/migrate.ts already has under the same signatures
-- — and both of upstream's bodies would have gone OVER the migrations' with
-- no error:
--
-- 1. thought_stats_summary() — migration 024's, which took this function from
--    this recipe and hardened it (a malformed topics array cannot raise, a
--    null element cannot break the aggregate).
--
-- 2. upsert_thought(text, jsonb, vector) — the 3-argument capture every write
--    on the SQL path runs. 004 created it; 005, 008, 021, 022 and 025 redefined
--    it, and upstream's 2026-04 body has none of theirs: no non-object guard,
--    no actor for the audit row, no model label, no window rule, no provenance
--    envelope. One paste of upstream's file and every capture after it wrote a
--    row missing all five, silently.
--
-- Nothing to apply on a migrated brain; the statements are removed and
-- scripts/check-fork-consistency.mjs check 7 fails the build if they return.
-- The recipe's Edge Function changes (README, step 2 onward) stand.
