#!/usr/bin/env bun
/**
 * gen-version.ts — writes server-portable/version.ts from db/version.mjs,
 * releases.json and db/migrations/ (SMD-2041).
 *
 * The server reports what it is: the `initialize` reply's version, the
 * `brain_info` tool and a keyed `GET /health`. db/version.mjs is where the
 * version is written, but it is node-only (node:crypto, node:fs) and the
 * Cloudflare Workers build bundles the server, so the server cannot import it.
 * Neither can it read releases.json or db/migrations/ at runtime: a Worker has
 * no filesystem, and the container image carries releases.json but not
 * db/migrations/ (server-portable/Dockerfile). So the three facts the server needs are
 * generated into a module with no imports at all — the version, the release
 * range it names, and the highest migration this tree carries — and
 * check-fork-consistency.ts's 17e round-trips it (regenerate in memory,
 * compare to the committed copy), as gen-tools.ts's tools.json is.
 *
 *   bun scripts/gen-version.ts        # rewrite server-portable/version.ts
 *
 * Rerun it after adding a migration or cutting a release; 17e names this
 * command when the file is stale.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { FORK_VERSION, readReleases } from "../db/version.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "server-portable", "version.ts");

/** The highest `NNN_*.sql` number in db/migrations/ — the tree's last migration. */
export function latestMigration(dir = join(ROOT, "db", "migrations")): number {
  const nums = readdirSync(dir).filter((n) => /^\d{3}_.*\.sql$/.test(n)).map((n) => Number(n.slice(0, 3)));
  if (nums.length === 0) throw new Error(`${dir} holds no NNN_*.sql migration`);
  return Math.max(...nums);
}

/** The exact contents server-portable/version.ts must have — one definition for the writer here and 17e. */
export function renderVersionTs(): string {
  const release = readReleases().find((r) => r.version === FORK_VERSION);
  const range = release?.range ? `[${release.range[0]}, ${release.range[1]}]` : "null";
  return [
    "// Generated by scripts/gen-version.ts from db/version.mjs, releases.json and",
    "// db/migrations/ — do not edit by hand; rerun it after a migration or a cut.",
    "// check-fork-consistency.ts's 17e round-trips it (SMD-2041). No imports: the",
    "// Workers build bundles it, and a Worker has none of those files to read.",
    "",
    "/** db/version.mjs's FORK_VERSION — the version this server reports. */",
    `export const FORK_VERSION = ${JSON.stringify(FORK_VERSION)};`,
    "",
    "/** The migration range releases.json records for FORK_VERSION, or null when it records none (a version bumped and not yet cut). */",
    `export const RELEASE_RANGE: readonly [number, number] | null = ${range};`,
    "",
    "/** The highest migration file in the tree this server was built from — what a brain migrated for it has applied. */",
    `export const LATEST_MIGRATION = ${latestMigration()};`,
    "",
  ].join("\n");
}

if (import.meta.main) {
  writeFileSync(OUT, renderVersionTs());
  console.log(`wrote ${OUT}`);
}
