// Generated by scripts/gen-version.ts from db/version.mjs, releases.json and
// db/migrations/ — do not edit by hand; rerun it after a migration or a cut.
// check-fork-consistency.ts's 17e round-trips it (SMD-2041). No imports: the
// Workers build bundles it, and a Worker has none of those files to read.

/** db/version.mjs's FORK_VERSION — the version this server reports. */
export const FORK_VERSION = "1.1.0+upstream.9543c29";

/** The migration range releases.json records for FORK_VERSION, or null when it records none (a version bumped and not yet cut). */
export const RELEASE_RANGE: readonly [number, number] | null = [49, 51];

/** The highest migration file in the tree this server was built from — what a brain migrated for it has applied. */
export const LATEST_MIGRATION = 53;
